/* Generated by Yosys 0.53 (git sha1 53c22ab7c, g++ 12.2.0-14 -fPIC -O3) */

module efuse_wb_mem_64x8(wb_rst_i, wb_clk_i, wb_adr_i, wb_dat_i, wb_we_i, wb_sel_i, wb_stb_i, wb_cyc_i, wb_dat_o, wb_ack_o);
  wire _000_;
  wire [6:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire [7:0] _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire [2:0] _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire [15:0] _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire [18:0] _061_;
  wire _062_;
  wire [2:0] _063_;
  wire [15:0] _064_;
  wire [7:0] _065_;
  wire _066_;
  wire [4:0] _067_;
  wire [18:0] _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire [11:0] _072_;
  wire [7:0] _073_;
  wire [2:0] _074_;
  wire [11:0] _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire [11:0] _079_;
  wire _080_;
  wire [2:0] _081_;
  wire [11:0] _082_;
  wire _083_;
  wire _084_;
  wire [11:0] _085_;
  wire [8:0] _086_;
  wire _087_;
  wire _088_;
  wire [2:0] _089_;
  wire [11:0] _090_;
  wire _091_;
  wire _092_;
  wire [7:0] _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire [7:0] _097_;
  wire _098_;
  wire [4:0] _099_;
  wire [2:0] _100_;
  wire [15:0] _101_;
  wire [11:0] _102_;
  wire [31:0] _103_;
  wire [7:0] _104_;
  reg [86:0] _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire [7:0] OUT;
  wire inpreset;
  wire [7:0] iprog_ena;
  wire isense;
  wire [86:0] r;
  wire [86:0] rin;
  output wb_ack_o;
  wire wb_ack_o;
  input [5:0] wb_adr_i;
  wire [5:0] wb_adr_i;
  input wb_clk_i;
  wire wb_clk_i;
  input wb_cyc_i;
  wire wb_cyc_i;
  input [7:0] wb_dat_i;
  wire [7:0] wb_dat_i;
  output [7:0] wb_dat_o;
  wire [7:0] wb_dat_o;
  input wb_rst_i;
  wire wb_rst_i;
  input wb_sel_i;
  wire wb_sel_i;
  input wb_stb_i;
  wire wb_stb;
  assign wb_stb = wb_stb_i & wb_cyc_i;
  input wb_we_i;
  wire wb_we;
  assign wb_we = wb_we_i & wb_sel_i[0];
  assign _087_ = r[10] & _076_;
  assign _074_ = _071_ ? 3'h0 : r[58:56];
  assign _075_ = _071_ ? 12'h000 : _072_;
  assign _077_ = r[58:56] == 3'h1;
  assign _078_ = r[86:77] == { 6'h00, r[69:66] };
  assign _079_ = r[86:75] + 12'h001;
  assign _080_ = _078_ ? 1'h1 : 1'h0;
  assign _081_ = _078_ ? 3'h3 : r[58:56];
  assign _082_ = _078_ ? 12'h000 : _079_;
  assign _098_ = ~ wb_rst_i;
  assign _083_ = r[58:56] == 3'h2;
  assign _084_ = r[86:77] == { 6'h00, r[73:70] };
  assign _109_ = r[9] & _098_;
  assign _085_ = r[86:75] + 12'h001;
  assign _086_ = _084_ ? { 1'h1, OUT } : { 1'h0, r[7:0] };
  assign _088_ = _084_ ? 1'h0 : 1'h1;
  assign _089_ = _084_ ? 3'h5 : r[58:56];
  assign _090_ = _084_ ? 12'h000 : _085_;
  assign _091_ = r[58:56] == 3'h3;
  assign _092_ = r[58:56] == 3'h5;
  function [7:0] \151 ;
    input [7:0] a;
    input [47:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \151  = b[7:0];
      6'b????1?:
        \151  = b[15:8];
      6'b???1??:
        \151  = b[23:16];
      6'b??1???:
        \151  = b[31:24];
      6'b?1????:
        \151  = b[39:32];
      6'b1?????:
        \151  = b[47:40];
      default:
        \151  = a;
    endcase
  endfunction
  assign _093_ = \151 (8'hxx, { r[7:0], _086_[7:0], r[7:0], r[7:0], r[7:0], r[7:0] }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  function [0:0] \155 ;
    input [0:0] a;
    input [5:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \155  = b[0:0];
      6'b????1?:
        \155  = b[1:1];
      6'b???1??:
        \155  = b[2:2];
      6'b??1???:
        \155  = b[3:3];
      6'b?1????:
        \155  = b[4:4];
      6'b1?????:
        \155  = b[5:5];
      default:
        \155  = a;
    endcase
  endfunction
  assign _094_ = \155 (1'hx, { 1'h0, _086_[8], 1'h0, r[8], 1'h0, _056_ }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  function [0:0] \158 ;
    input [0:0] a;
    input [5:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \158  = b[0:0];
      6'b????1?:
        \158  = b[1:1];
      6'b???1??:
        \158  = b[2:2];
      6'b??1???:
        \158  = b[3:3];
      6'b?1????:
        \158  = b[4:4];
      6'b1?????:
        \158  = b[5:5];
      default:
        \158  = a;
    endcase
  endfunction
  assign _095_ = \158 (1'hx, { r[9], r[9], _080_, r[9], r[9], r[9] }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  function [0:0] \161 ;
    input [0:0] a;
    input [5:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \161  = b[0:0];
      6'b????1?:
        \161  = b[1:1];
      6'b???1??:
        \161  = b[2:2];
      6'b??1???:
        \161  = b[3:3];
      6'b?1????:
        \161  = b[4:4];
      6'b1?????:
        \161  = b[5:5];
      default:
        \161  = a;
    endcase
  endfunction
  assign _096_ = \161 (1'hx, { r[10], _088_, r[10], r[10], r[10], r[10] }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  function [7:0] \164 ;
    input [7:0] a;
    input [47:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \164  = b[7:0];
      6'b????1?:
        \164  = b[15:8];
      6'b???1??:
        \164  = b[23:16];
      6'b??1???:
        \164  = b[31:24];
      6'b?1????:
        \164  = b[39:32];
      6'b1?????:
        \164  = b[47:40];
      default:
        \164  = a;
    endcase
  endfunction
  assign _097_ = \164 (8'hxx, { r[18:11], r[18:11], r[18:11], _073_, wb_dat_i, 8'h00 }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  function [4:0] \167 ;
    input [4:0] a;
    input [29:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \167  = b[4:0];
      6'b????1?:
        \167  = b[9:5];
      6'b???1??:
        \167  = b[14:10];
      6'b??1???:
        \167  = b[19:15];
      6'b?1????:
        \167  = b[24:20];
      6'b1?????:
        \167  = b[29:25];
      default:
        \167  = a;
    endcase
  endfunction
  assign _099_ = \167 (5'hxx, { r[23:19], r[23:19], r[23:19], r[23:19], r[23:19], _067_ }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  function [2:0] \170 ;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \170  = b[2:0];
      6'b????1?:
        \170  = b[5:3];
      6'b???1??:
        \170  = b[8:6];
      6'b??1???:
        \170  = b[11:9];
      6'b?1????:
        \170  = b[14:12];
      6'b1?????:
        \170  = b[17:15];
      default:
        \170  = a;
    endcase
  endfunction
  assign _100_ = \170 (3'hx, { 3'h0, _089_, _081_, _074_, 3'h1, _068_[2:0] }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  function [15:0] \174 ;
    input [15:0] a;
    input [95:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \174  = b[15:0];
      6'b????1?:
        \174  = b[31:16];
      6'b???1??:
        \174  = b[47:32];
      6'b??1???:
        \174  = b[63:48];
      6'b?1????:
        \174  = b[79:64];
      6'b1?????:
        \174  = b[95:80];
      default:
        \174  = a;
    endcase
  endfunction
  assign _101_ = \174 (16'hxxxx, { r[74:59], r[74:59], r[74:59], r[74:59], r[74:59], _068_[18:3] }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  function [11:0] \177 ;
    input [11:0] a;
    input [71:0] b;
    input [5:0] s;
    (* parallel_case *)
    casez (s)
      6'b?????1:
        \177  = b[11:0];
      6'b????1?:
        \177  = b[23:12];
      6'b???1??:
        \177  = b[35:24];
      6'b??1???:
        \177  = b[47:36];
      6'b?1????:
        \177  = b[59:48];
      6'b1?????:
        \177  = b[71:60];
      default:
        \177  = a;
    endcase
  endfunction
  assign _102_ = \177 (12'hxxx, { r[86:75], _090_, _082_, _075_, r[86:75], r[86:75] }, { _092_, _091_, _083_, _077_, _070_, _069_ });
  assign _103_ = 32'd1 << { 27'h0000000, _099_ };
  always @(posedge wb_clk_i, posedge wb_rst_i)
    if (wb_rst_i) _105_ <= 87'h0000cc8000000000000200;
    else _105_ <= rin;
  assign _106_ = ~ _103_[4];
  assign _107_ = ~ _103_[3];
  assign _108_ = _106_ & _107_;
  assign _110_ = _106_ & _103_[3];
  assign _111_ = _103_[4] & _107_;
  assign _112_ = _103_[4] & _103_[3];
  assign _113_ = ~ _103_[2];
  assign _114_ = _108_ & _113_;
  assign _115_ = _108_ & _103_[2];
  assign _116_ = _110_ & _113_;
  assign _117_ = _110_ & _103_[2];
  assign _118_ = _111_ & _113_;
  assign _119_ = _111_ & _103_[2];
  assign _121_ = _112_ & _113_;
  assign _122_ = _112_ & _103_[2];
  assign _123_ = ~ _103_[1];
  assign _124_ = _114_ & _123_;
  assign _125_ = _114_ & _103_[1];
  assign _126_ = _115_ & _123_;
  assign _127_ = _115_ & _103_[1];
  assign _128_ = _116_ & _123_;
  assign _129_ = _116_ & _103_[1];
  assign _130_ = _117_ & _123_;
  assign _132_ = _117_ & _103_[1];
  assign _133_ = _118_ & _123_;
  assign _134_ = _118_ & _103_[1];
  assign _135_ = _119_ & _123_;
  assign _136_ = _119_ & _103_[1];
  assign _137_ = _121_ & _123_;
  assign _138_ = _121_ & _103_[1];
  assign _139_ = _122_ & _123_;
  assign _140_ = _122_ & _103_[1];
  assign _141_ = ~ _103_[0];
  assign _143_ = _124_ & _141_;
  assign _144_ = _124_ & _103_[0];
  assign _145_ = _125_ & _141_;
  assign _146_ = _125_ & _103_[0];
  assign _147_ = _126_ & _141_;
  assign _148_ = _126_ & _103_[0];
  assign _149_ = _127_ & _141_;
  assign _150_ = _127_ & _103_[0];
  assign _151_ = _128_ & _141_;
  assign _152_ = _128_ & _103_[0];
  assign _002_ = _129_ & _141_;
  assign _003_ = _129_ & _103_[0];
  assign _004_ = _130_ & _141_;
  assign _005_ = _130_ & _103_[0];
  assign _006_ = _132_ & _141_;
  assign _007_ = _132_ & _103_[0];
  assign _008_ = _133_ & _141_;
  assign _009_ = _133_ & _103_[0];
  assign _010_ = _134_ & _141_;
  assign _011_ = _134_ & _103_[0];
  assign _013_ = _135_ & _141_;
  assign _014_ = _135_ & _103_[0];
  assign _015_ = _136_ & _141_;
  assign _016_ = _136_ & _103_[0];
  assign _017_ = _137_ & _141_;
  assign _018_ = _137_ & _103_[0];
  assign _019_ = _138_ & _141_;
  assign _020_ = _138_ & _103_[0];
  assign _021_ = _139_ & _141_;
  assign _022_ = _139_ & _103_[0];
  assign _024_ = _140_ & _141_;
  assign _025_ = _140_ & _103_[0];
  assign _026_ = _143_ ? 1'h1 : 1'h0;
  assign _027_ = _144_ ? 1'h1 : 1'h0;
  assign _028_ = _145_ ? 1'h1 : 1'h0;
  assign _029_ = _146_ ? 1'h1 : 1'h0;
  assign _030_ = _147_ ? 1'h1 : 1'h0;
  assign _031_ = _148_ ? 1'h1 : 1'h0;
  assign _032_ = _149_ ? 1'h1 : 1'h0;
  assign _033_ = _150_ ? 1'h1 : 1'h0;
  assign _035_ = _151_ ? 1'h1 : 1'h0;
  assign _036_ = _152_ ? 1'h1 : 1'h0;
  assign _037_ = _002_ ? 1'h1 : 1'h0;
  assign _038_ = _003_ ? 1'h1 : 1'h0;
  assign _039_ = _004_ ? 1'h1 : 1'h0;
  assign _040_ = _005_ ? 1'h1 : 1'h0;
  assign _041_ = _006_ ? 1'h1 : 1'h0;
  assign _042_ = _007_ ? 1'h1 : 1'h0;
  assign _043_ = _008_ ? 1'h1 : 1'h0;
  assign _044_ = _009_ ? 1'h1 : 1'h0;
  assign _046_ = _010_ ? 1'h1 : 1'h0;
  assign _047_ = _011_ ? 1'h1 : 1'h0;
  assign _048_ = _013_ ? 1'h1 : 1'h0;
  assign _049_ = _014_ ? 1'h1 : 1'h0;
  assign _050_ = _015_ ? 1'h1 : 1'h0;
  assign _051_ = _016_ ? 1'h1 : 1'h0;
  assign _052_ = _017_ ? 1'h1 : 1'h0;
  assign _053_ = _018_ ? 1'h1 : 1'h0;
  assign _054_ = _019_ ? 1'h1 : 1'h0;
  assign _055_ = _020_ ? 1'h1 : 1'h0;
  assign _057_ = _021_ ? 1'h1 : 1'h0;
  assign _058_ = _022_ ? 1'h1 : 1'h0;
  assign _059_ = _024_ ? 1'h1 : 1'h0;
  assign _060_ = _025_ ? 1'h1 : 1'h0;
  assign _120_ = ~ r[74];
  assign _131_ = ~ wb_adr_i[5];
  assign _142_ = ~ wb_adr_i[0];
  assign _000_ = ~ wb_rst_i;
  assign _001_ = _142_ ? r[65:59] : wb_dat_i[6:0];
  assign _012_ = _142_ ? { wb_dat_i[3:0], wb_dat_i[7:4] } : r[73:66];
  assign _023_ = _142_ ? r[74] : wb_dat_i[7];
  assign _034_ = _131_ ? 3'h4 : r[58:56];
  assign _045_ = _131_ ? r[74:59] : { _023_, _012_, _001_ };
  assign _056_ = _066_ ? 1'h1 : 1'h0;
  assign _061_ = _120_ ? { _045_, _034_ } : r[74:56];
  assign _065_ = r[18:11] & { _000_, _000_, _000_, _000_, _000_, _000_, _000_, _000_ };
  assign _062_ = _120_ & wb_we;
  assign _063_ = wb_we ? _061_[2:0] : 3'h2;
  assign _064_ = wb_we ? _061_[18:3] : r[74:59];
  assign _066_ = _062_ & wb_stb;
  assign _067_ = wb_stb ? wb_adr_i[4:0] : r[23:19];
  assign _068_ = wb_stb ? { _064_, _063_ } : r[74:56];
  assign _069_ = r[58:56] == 3'h0;
  assign _070_ = r[58:56] == 3'h4;
  assign _076_ = ~ wb_rst_i;
  assign _071_ = r[86:80] == r[65:59];
  assign _072_ = r[86:75] + 12'h001;
  assign _073_ = _071_ ? 8'h00 : r[18:11];
  efuse_array_64x8  efuse_rom_inst (
    .BIT_SEL(r[55:24]),
    .COL_PROG_N(iprog_ena),
    .OUT(_104_),
    .PRESET_N(inpreset),
    .SENSE(isense)
  );
  assign r = _105_;
  assign rin = { _102_, _101_, _100_, _060_, _059_, _058_, _057_, _055_, _054_, _053_, _052_, _051_, _050_, _049_, _048_, _047_, _046_, _044_, _043_, _042_, _041_, _040_, _039_, _038_, _037_, _036_, _035_, _033_, _032_, _031_, _030_, _029_, _028_, _027_, _026_, _099_, _097_, _096_, _095_, _094_, _093_ };
  assign OUT = _104_;
  assign iprog_ena = _065_;
  assign inpreset = _109_;
  assign isense = _087_;
  assign wb_dat_o = r[7:0];
  assign wb_ack_o = r[8];
endmodule
